create table OSP_USER_CONNECT
(
    ID               NUMBER(10) not null
        constraint PK_OSP_USER_CONNECT
        primary key,
    EMAIL            VARCHAR2(50),
    LOGUSER          VARCHAR2(50),
    FULLNAME         VARCHAR2(50),
    LOGPASS          VARCHAR2(50),
    LOGKEY           VARCHAR2(50),
    STATUS           VARCHAR2(50),
    DATE_CONNEXION   DATE,
    DATE_DECONNEXION DATE,
    ACTIF            NUMBER(10, 2),
    CREATEDAT        TIMESTAMP(6),
    UPDATEDAT        TIMESTAMP(6),
)
CREATE SEQUENCE osp_role_seq MINVALUE 1

CREATE TABLE OSP_ROLE
(
    ID   NUMBER(10) not null
        constraint PK_OSP_ROLE
        primary key,
    CODE VARCHAR(25 BYTE
) not null ENABLE,
                ROLE_DESC VARCHAR2(255 BYTE) NOT NULL ENABLE,
                ACTIF NUMBER(1,0) NOT NULL ENABLE

)


CREATE TABLE OSP_USER_ROLE
(
    OSP_USER_CONNECT_ID NUMBER(10,0) NOT NULL ENABLE,
    OSP_ROLE_ID NUMBER(10,0)  NOT NULL ENABLE,
)

ALTER TABLE OSP_USER_ROLE
    ADD CONSTRAINT PK_OSP_USER_ROLE_ID PRIMARY KEY (OSP_USER_CONNECT_ID, OSP_ROLE_ID);
ALTER TABLE OSP_USER_ROLE
    ADD CONSTRAINT FK_OSP_USER_CONNECT_ID_1 FOREIGN KEY (OSP_USER_CONNECT_ID) REFERENCES OSP_USER_CONNECT (ID);
ALTER TABLE OSP_USER_ROLE
    ADD CONSTRAINT FK_OSP_ROLE_ID_1 FOREIGN KEY (OSP_ROLE_ID) REFERENCES OSP_ROLE (ID);

alter table OSP_ROLE
add   CREATEDAT  TIMESTAMP(6),

alter table OSP_ROLE
    add   UPDATEDAT  TIMESTAMP(6),