create table TICKETING_PAIEMENT
(
    ID                      NUMBER(10) not null
        constraint PK_TICKETING_PAIEMENT
        primary key,
    CODE_TICKET             VARCHAR2(4000),
    MONTANT                 NUMBER(10, 2),
    TYPE_PAIEMENT           VARCHAR2(50),
    REFERENCE               VARCHAR2(200),
    TRANSACTION_ID          VARCHAR2(200),
    TELEPHONE               VARCHAR2(50),
    OPERATEUR               VARCHAR2(200),
    DATE_EXPIRATION         TIMESTAMP(6),
    PERSONNE_PHYSIQUE       NUMBER(1),
    CREATEDAT               TIMESTAMP(6),
    UPDATEDAT               TIMESTAMP(6),
    TICKETING_PRESTATION_ID NUMBER(10),
    TICKETING_USER_ID       NUMBER(10)
        constraint FK_TICKETING_USER
        references TICKETING_USER
)
    /

create table TICKETING_PRESTATION
(
    ID                           NUMBER(10) not null
        constraint PK_TICKETING_PRESTATION
        primary key,
    DESIGNATION                  VARCHAR2(4000),
    PERSONNE_PHYSIQUE            NUMBER(1),
    CREATEDAT                    TIMESTAMP(6),
    UPDATEDAT                    TIMESTAMP(6),
    TICKETING_TYPE_PRESTATION_ID NUMBER(10)
)
    /

create table TICKETING_TYPE_PRESTATION
(
    ID              NUMBER(10) not null
        constraint PK_TICKETING_TYPE_PRESTATION
        primary key,
    DESIGNATION     VARCHAR2(4000),
    COMPTE_ACREDITE VARCHAR2(50),
    PRIX_UNITAIRE   NUMBER(10, 2),
    CREATEDAT       TIMESTAMP(6),
    UPDATEDAT       TIMESTAMP(6)
)
    /

create table TICKETING_USER
(
    ID   NUMBER(10) not null
        constraint PK_TICKETING_CAISSIER
        primary key,
    USERNAME         VARCHAR2(50),
    PASSWORD         VARCHAR2(50),
    NOM              VARCHAR2(50),
    PRENOM           VARCHAR2(50),
    TELEPHONE        VARCHAR2(50),
    FONCTION         VARCHAR2(50),
    DATE_CONNEXION   DATE,
    DATE_DECONNEXION DATE,
    ACTIF            NUMBER(10, 2),
    CREATEDAT        TIMESTAMP(6),
    UPDATEDAT        TIMESTAMP(6),
    ROLE             VARCHAR2(255)
)
CREATE SEQUENCE  ticketing_role_seq  MINVALUE 1

CREATE TABLE TICKETING_ROLE(
                CODE  VARCHAR(25 BYTE) not null ENABLE,
                ROLE_DESC VARCHAR2(255 BYTE) NOT NULL ENABLE,
                ACTIF NUMBER(1,0) NOT NULL ENABLE

)

ALTER TABLE TICKETING_ROLE ADD CONSTRAINT PK_TICKETING_ROLE PRIMARY KEY (CODE);


CREATE TABLE TICKETING_USER_ROLE(
                 TICKETING_USER_ID NUMBER(10,0) NOT NULL ENABLE,
                 TICKETING_ROLE_ID VARCHAR2(25 BYTE) NOT NULL ENABLE,
)

ALTER TABLE TICKETING_USER_ROLE ADD CONSTRAINT PK_TICKETING_USER_ROLE_ID PRIMARY KEY (TICKETING_USER_ID, TICKETING_ROLE_ID);
ALTER TABLE TICKETING_USER_ROLE ADD CONSTRAINT FK_TICKETING_USER_ID_1 FOREIGN KEY (TICKETING_USER_ID) REFERENCES TICKETING_USER(ID);
ALTER TABLE TICKETING_USER_ROLE ADD CONSTRAINT FK_TICKETING_ROLE_ID_1 FOREIGN KEY (TICKETING_ROLE_ID) REFERENCES TICKETING_ROLE(ID);


ALTER TABLE TICKETING_TYPE_PRESTATION ADD CONSTRAINT FK_TICKETING_PRESTATION_ID FOREIGN KEY (TICKETING_PRESTATION_ID) REFERENCES TICKETING_PRESTATION(ID);

ALTER TABLE TICKETING_PAIEMENT ADD CONSTRAINT FK_TICKETING_TYPE_PRESTATION_ID FOREIGN KEY (TICKETING_TYPE_PRESTATION_ID) REFERENCES TICKETING_TYPE_PRESTATION(ID);


TICKETING_PRESTATION_ID


///// Table notification

create table TICKETING_RECETTES
(
    ID   NUMBER(10) not null
        constraint PK_TICKETING_RECETTES
        primary key,
    CODE_TICKET             VARCHAR2(255),
    MONTANT                 NUMBER(10, 2),
    REFERENCE               VARCHAR2(200),
    TRANSACTION_ID          VARCHAR2(200),
    TELEPHONE               VARCHAR2(50),
    OPERATEUR               VARCHAR2(200),
    DATE_PAIEMENT           TIMESTAMP(6),
    CREATEDAT               TIMESTAMP(6),

)

CREATE SEQUENCE  ticketing_recettes_seq  MINVALUE 1

alter table TICKETING_PAIEMENT add column recette varchar2(200);