CREATE TABLE "SIPEDB"."TICKETING_TYPE_PRESTATION"
(
    "ID"              NUMBER(10, 0) NOT NULL ENABLE,
    "DESIGNATION"     VARCHAR2(4000 BYTE),
    "COMPTE_ACREDITE" VARCHAR2(50 BYTE),
    "PRIX_UNITAIRE"   NUMBER(10, 2),
    "CREATEDAT"       TIMESTAMP(6),
    "UPDATEDAT"       TIMESTAMP(6),
    CONSTRAINT "TICKETING_TYPE_PRESTATION_SEQ" PRIMARY KEY ("ID")
)

CREATE SEQUENCE TICKETING_TYPE_PRESTATION_SEQ START WITH 1;


CREATE TABLE "SIPEDB"."TICKETING_PRESTATION"
(
    "ID"                 NUMBER(10, 0) NOT NULL ENABLE,
    "DESIGNATION"        VARCHAR2(4000 BYTE),
    "PERSONNE_PHYSIQUE"  VARCHAR2(50 BYTE),
    "CREATEDAT"          TIMESTAMP(6),
    "UPDATEDAT"          TIMESTAMP(6),
    "TYPE_PRESTATION_ID" NUMBER(10, 0),
    CONSTRAINT "TICKETING_PRESTATION_SEQ" PRIMARY KEY ("ID")
)

CREATE SEQUENCE TICKETING_PRESTATION_SEQ START WITH 1;


CREATE TABLE "SIPEDB"."TICKETING_CAISSIER"
(
    "ID"               NUMBER(10, 0) NOT NULL ENABLE,
    "USERNAME"         VARCHAR2(50 BYTE),
    "PASSWORD"         VARCHAR2(50 BYTE),
    "NAME"             VARCHAR2(50 BYTE),
    "PRENOM"           VARCHAR2(50 BYTE),
    "TELEPHONE"        VARCHAR2(50 BYTE),
    "FONCTION"         VARCHAR2(50 BYTE),
    "DATE_CONNEXION"   DATE,
    "DATE_DECONNEXION" DATE,
    "ACTIF"            NUMBER(10, 2),
    "CREATEDAT"        TIMESTAMP(6),
    "UPDATEDAT"        TIMESTAMP(6),
    CONSTRAINT "TICKETING_CAISSIER_SEQ" PRIMARY KEY ("ID")
)

CREATE SEQUENCE TICKETING_CAISSIER_SEQ START WITH 1;


CREATE TABLE "SIPEDB"."TICKETING_PAIEMENT"
(
    "ID"                NUMBER(10, 0) NOT NULL ENABLE,
    "CODE_TICKET"       VARCHAR2(4000 BYTE),
    "MONTANT"           NUMBER(10, 2),
    "TYPE_PAIEMENT"     VARCHAR2(50 BYTE),
    "REFERENCE"         VARCHAR2(200 BYTE),
    "TRANSACTION_ID"    VARCHAR2(200 BYTE),
    "TELEPHONE"         VARCHAR2(50 BYTE),
    "OPERATEUR"         VARCHAR2(200 BYTE),
    "DATE_EXPIRATION"   TIMESTAMP(6),
    "PERSONNE_PHYSIQUE" VARCHAR2(50 BYTE),
    "CREATEDAT"         TIMESTAMP(6),
    "UPDATEDAT"         TIMESTAMP(6),
    "PRESTATION_ID"     NUMBER(10, 0),
    "CAISSIER_ID"       NUMBER(10, 0),
    CONSTRAINT "TICKETING_PAIEMENT_SEQ" PRIMARY KEY ("ID")
)
